import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const supabase=createClient("https://jfomzksnsjytqhsuaqto.supabase.co","sb_publishable_zSAgcLcAEmNg655NHVt2YQ__nYB-qhg");
const $=x=>document.getElementById(x);let mode="login",user=null,month=new Date(new Date().getFullYear(),new Date().getMonth(),1),cats=[],editingId=null;
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const start=()=>new Date(month.getFullYear(),month.getMonth(),1).toISOString().slice(0,10),end=()=>new Date(month.getFullYear(),month.getMonth()+1,0).toISOString().slice(0,10);
const isoAddMonths=(date,n)=>{const d=new Date(date+"T12:00:00");d.setMonth(d.getMonth()+n);return d.toISOString().slice(0,10)};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));$("nameWrap").classList.toggle("hide",mode!=="signup");$("authBtn").textContent=mode==="login"?"Entrar":"Criar conta";$("authMsg").textContent=""});
$("authForm").onsubmit=async e=>{e.preventDefault();$("authMsg").textContent="Processando...";let email=$("email").value.trim(),password=$("password").value,name=$("name").value.trim();let r=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{nome:name},emailRedirectTo:"https://portal-financeiro-bo7dygkvw-24nvnvnhp9-8443.vercel.app/"}});if(r.error){$("authMsg").textContent=r.error.message;return}if(mode==="signup"&&!r.data.session){$("authMsg").style.color="#8fe7b3";$("authMsg").textContent="Conta criada. Verifique seu e-mail para confirmar."}};
$("logout").onclick=()=>supabase.auth.signOut();
$("prev").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);load()};
$("next").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);load()};
function openNew(){editingId=null;$("modalTitle").textContent="Novo lançamento";$("txForm").reset();$("installments").value=1;$("modal").classList.remove("hide");$("date").value=new Date().toISOString().slice(0,10);$("txMsg").textContent="";renderCats()}
$("add").onclick=openNew;
$("close").onclick=()=>$("modal").classList.add("hide");
$("modal").onclick=e=>{if(e.target===$("modal"))$("modal").classList.add("hide")};
$("type").onchange=renderCats;
async function loadCats(){let r=await supabase.from("categorias").select("id,nome,tipo").eq("user_id",user.id).eq("ativa",true).order("nome");if(r.error){$("txMsg").textContent=r.error.message;return}cats=r.data||[];renderCats()}
function renderCats(){let t=$("type").value;if(!$("cat"))return;$("cat").innerHTML=cats.filter(c=>c.tipo===t).map(c=>'<option value="'+c.id+'">'+c.nome+"</option>").join("")}
async function editTx(id){let r=await supabase.from("lancamentos").select("id,data,tipo,descricao,valor,categoria_id,recorrente,recorrencia,parcela_atual,total_parcelas").eq("id",id).eq("user_id",user.id).single();if(r.error){alert(r.error.message);return}let x=r.data;editingId=x.id;$("modalTitle").textContent="Editar lançamento";$("type").value=x.tipo;renderCats();$("cat").value=x.categoria_id||"";$("date").value=x.data;$("value").value=x.valor;$("desc").value=x.descricao||"";$("rec").checked=!!x.recorrente;$("installments").value=x.total_parcelas||1;$("txMsg").textContent="";$("modal").classList.remove("hide")}
async function deleteTx(id){if(!confirm("Excluir este lançamento?"))return;let r=await supabase.from("lancamentos").delete().eq("id",id).eq("user_id",user.id);if(r.error){alert(r.error.message);return}await load()}
$("txForm").onsubmit=async e=>{e.preventDefault();$("txMsg").textContent="Salvando...";const tipo=$("type").value,data=$("date").value,valor=Number($("value").value),descricao=$("desc").value.trim(),categoria_id=$("cat").value||null,recorrente=$("rec").checked,total=Math.max(1,Math.min(120,Number($("installments").value)||1));
if(editingId){let r=await supabase.from("lancamentos").update({tipo,data,valor,descricao,categoria_id,recorrente,recorrencia:recorrente?"mensal":null,parcela_atual:total>1?1:null,total_parcelas:total>1?total:null}).eq("id",editingId).eq("user_id",user.id);if(r.error){$("txMsg").textContent=r.error.message;return}}
else{const rows=Array.from({length:total},(_,i)=>({user_id:user.id,tipo,data:isoAddMonths(data,i),valor,descricao:total>1?descricao+" ("+(i+1)+"/"+total+")":descricao,categoria_id,recorrente:total>1?false:recorrente,recorrencia:total>1?"mensal":(recorrente?"mensal":null),parcela_atual:total>1?i+1:null,total_parcelas:total>1?total:null,status:"confirmado"}));let r=await supabase.from("lancamentos").insert(rows);if(r.error){$("txMsg").textContent=r.error.message;return}}
$("txForm").reset();$("modal").classList.add("hide");editingId=null;await load()};
async function load(){let label=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(month);$("monthLabel").textContent=label.charAt(0).toUpperCase()+label.slice(1);
let r=await supabase.from("lancamentos").select("id,data,tipo,descricao,valor,status,categoria_id,recorrente,parcela_atual,total_parcelas,categorias(nome)").eq("user_id",user.id).gte("data",start()).lte("data",end()).neq("status","cancelado").order("data",{ascending:false});if(r.error){console.error(r.error);return}
let rows=r.data||[],a=0,b=0,c=0;rows.forEach(x=>{if(x.tipo==="receita")a+=+x.valor;if(x.tipo==="despesa")b+=+x.valor;if(x.tipo==="investimento")c+=+x.valor});$("income").textContent=money(a);$("expense").textContent=money(b);$("invest").textContent=money(c);$("balance").textContent=money(a-b-c);$("count").textContent=rows.length+" lançamento"+(rows.length===1?"":"s");
$("list").innerHTML=rows.length?rows.map(x=>'<div class="tx"><div><strong>'+esc(x.descricao)+'</strong><small>'+new Date(x.data+"T12:00:00").toLocaleDateString("pt-BR")+" · "+esc(x.categorias?.nome||"Sem categoria")+(x.recorrente?" · 🔄 mensal":"")+'</small></div><div class="txRight"><div class="amount '+x.tipo+'">'+(x.tipo==="receita"?"+":"-")+money(x.valor)+'</div><div class="txActions"><button data-edit="'+x.id+'">Editar</button><button data-delete="'+x.id+'">Excluir</button></div></div></div>').join(""):'<div class="empty">Nenhum lançamento neste mês.</div>';
document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editTx(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteTx(b.dataset.delete))}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
async function enter(u){user=u;$("authView").classList.add("hide");$("app").classList.remove("hide");$("welcome").textContent="Olá, "+(u.user_metadata?.nome||u.email.split("@")[0]);await loadCats();await load()}
const s=await supabase.auth.getSession();if(s.data.session)enter(s.data.session.user);supabase.auth.onAuthStateChange((e,s)=>{if(s)enter(s.user);else{$("app").classList.add("hide");$("authView").classList.remove("hide")}});
// Portal Financeiro — lançamentos: editar, excluir, parcelas e recorrência
