import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const supabase=createClient("https://jfomzksnsjytqhsuaqto.supabase.co","sb_publishable_zSAgcLcAEmNg655NHVt2YQ__nYB-qhg");
const $=id=>document.getElementById(id);let user=null,mode="login",month=new Date(new Date().getFullYear(),new Date().getMonth(),1),cats=[],editingId=null,editingFixed=null,editingCat=null,editingGoal=null,cacheRows=[];
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const iso=d=>d instanceof Date?d.toISOString().slice(0,10):d;
const start=()=>iso(new Date(month.getFullYear(),month.getMonth(),1)),end=()=>iso(new Date(month.getFullYear(),month.getMonth()+1,0));
const addMonths=(date,n)=>{let d=new Date(date+"T12:00:00");d.setMonth(d.getMonth()+n);return iso(d)};
const toast=m=>{let x=document.createElement("div");x.className="toast";x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),2600)};
const openModal=id=>$(id).classList.remove("hide"),closeModal=id=>$(id).classList.add("hide");
const page=p=>{document.querySelectorAll(".page").forEach(x=>x.classList.toggle("activePage",x.id==="page-"+p));document.querySelectorAll(".navBtn").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(p==="dashboard")loadDashboard();if(p==="lancamentos")loadTransactions();if(p==="fixas")loadFixed();if(p==="categorias")loadCategories();if(p==="metas")loadGoals();if(p==="reserva")loadReserve();if(p==="relatorios")loadReports();if(p==="conta")loadProfile()};
document.querySelectorAll(".navBtn").forEach(b=>b.onclick=()=>page(b.dataset.page));
document.querySelectorAll("[data-page-go]").forEach(b=>b.onclick=()=>page(b.dataset.pageGo));
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));$("nameWrap").classList.toggle("hide",mode!=="signup");$("authBtn").textContent=mode==="login"?"Entrar":"Criar conta";$("authMsg").textContent=""});
$("authForm").onsubmit=async e=>{e.preventDefault();$("authMsg").textContent="Processando...";let email=$("email").value.trim(),password=$("password").value,name=$("name").value.trim();let r=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{nome:name},emailRedirectTo:"https://portal-financeiro-agvkwr8x7-24nvnvnhp9-8443.vercel.app/"}});if(r.error){$("authMsg").textContent=r.error.message;return}if(mode==="signup"&&!r.data.session){$("authMsg").style.color="#8fe7b3";$("authMsg").textContent="Conta criada. Verifique seu e-mail para confirmar."}};
$("logout").onclick=()=>supabase.auth.signOut();
$("prev").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);page("dashboard")};
$("next").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);page("dashboard")};
$("dashAdd").onclick=()=>openTx();$("add").onclick=()=>openTx();$("close").onclick=()=>closeModal("modal");$("modal").onclick=e=>{if(e.target===$("modal"))closeModal("modal")};
$("type").onchange=renderCats;$("filterType").onchange=loadTransactions;$("filterSearch").oninput=loadTransactions;
async function loadCats(){let r=await supabase.from("categorias").select("id,nome,tipo,ativa").eq("user_id",user.id).order("tipo").order("nome");if(r.error)return;cats=r.data||[];renderCats();renderFixedCats()}
function renderCats(){let t=$("type").value;$("cat").innerHTML=cats.filter(c=>c.tipo===t&&c.ativa).map(c=>'<option value="'+c.id+'">'+esc(c.nome)+"</option>").join("")}
function renderFixedCats(){$("fixedCat").innerHTML=cats.filter(c=>c.tipo==="despesa"&&c.ativa).map(c=>'<option value="'+c.id+'">'+esc(c.nome)+"</option>").join("")}
function openTx(id=null){editingId=id; $("modalTitle").textContent=id?"Editar lançamento":"Novo lançamento";$("txForm").reset();$("installments").value=1;$("date").value=iso(new Date());$("txMsg").textContent="";if(id)editTx(id);else{renderCats();openModal("modal")}}
async function editTx(id){let r=await supabase.from("lancamentos").select("*").eq("id",id).eq("user_id",user.id).single();if(r.error){toast(r.error.message);return}let x=r.data;editingId=x.id;$("modalTitle").textContent="Editar lançamento";$("type").value=x.tipo;renderCats();$("cat").value=x.categoria_id||"";$("date").value=x.data;$("value").value=x.valor;$("desc").value=x.descricao||"";$("rec").checked=!!x.recorrente;$("installments").value=x.total_parcelas||1;openModal("modal")}
$("txForm").onsubmit=async e=>{e.preventDefault();$("txMsg").textContent="Salvando...";const tipo=$("type").value,data=$("date").value,valor=Number($("value").value),descricao=$("desc").value.trim(),categoria_id=$("cat").value||null,recorrente=$("rec").checked,total=Math.max(1,Math.min(120,Number($("installments").value)||1));let r;if(editingId)r=await supabase.from("lancamentos").update({tipo,data,valor,descricao,categoria_id,recorrente,recorrencia:recorrente?"mensal":null,parcela_atual:total>1?1:null,total_parcelas:total>1?total:null}).eq("id",editingId).eq("user_id",user.id);else{let rows=Array.from({length:total},(_,i)=>({user_id:user.id,tipo,data:addMonths(data,i),valor,descricao:total>1?descricao+" ("+(i+1)+"/"+total+")":descricao,categoria_id,recorrente:total>1?false:recorrente,recorrencia:total>1?"mensal":recorrente?"mensal":null,parcela_atual:total>1?i+1:null,total_parcelas:total>1?total:null,status:"confirmado"}));r=await supabase.from("lancamentos").insert(rows)}if(r.error){$("txMsg").textContent=r.error.message;return}closeModal("modal");editingId=null;toast("Lançamento salvo");loadDashboard();loadTransactions()};
async function deleteTx(id){if(!confirm("Excluir este lançamento?"))return;let r=await supabase.from("lancamentos").delete().eq("id",id).eq("user_id",user.id);if(r.error)toast(r.error.message);else{toast("Lançamento excluído");loadDashboard();loadTransactions()}}
async function loadTransactions(){if(!user)return;let q=supabase.from("lancamentos").select("id,data,tipo,descricao,valor,status,categoria_id,recorrente,parcela_atual,total_parcelas,categorias(nome)").eq("user_id",user.id).gte("data",start()).lte("data",end()).neq("status","cancelado").order("data",{ascending:false});let r=await q;if(r.error){$("list").innerHTML='<div class="empty">'+esc(r.error.message)+"</div>";return}cacheRows=r.data||[];let type=$("filterType").value,search=$("filterSearch").value.trim().toLowerCase();let rows=cacheRows.filter(x=>(!type||x.tipo===type)&&(!search||String(x.descricao||"").toLowerCase().includes(search)));$("count").textContent=rows.length+" lançamento"+(rows.length===1?"":"s");$("list").innerHTML=rows.length?rows.map(txHtml).join(""):'<div class="empty">Nenhum lançamento neste mês.</div>';bindTx()}
function txHtml(x){return '<div class="tx"><div><strong>'+esc(x.descricao)+'</strong><small>'+new Date(x.data+"T12:00:00").toLocaleDateString("pt-BR")+" · "+esc(x.categorias?.nome||"Sem categoria")+(x.parcela_atual? " · "+x.parcela_atual+"/"+x.total_parcelas:"")+(x.recorrente?" · 🔄 mensal":"")+'</small></div><div class="txRight"><div class="amount '+x.tipo+'">'+(x.tipo==="receita"?"+":"-")+money(x.valor)+'</div><div class="actions"><button data-edit="'+x.id+'">Editar</button><button data-delete="'+x.id+'">Excluir</button></div></div></div>'}
function bindTx(){document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openTx(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>deleteTx(b.dataset.delete))}
async function loadDashboard(){if(!user)return;let r=await supabase.from("lancamentos").select("id,data,tipo,descricao,valor,status,categorias(nome)").eq("user_id",user.id).gte("data",start()).lte("data",end()).neq("status","cancelado").order("data",{ascending:false});if(r.error)return;let rows=r.data||[],a=0,b=0,c=0;rows.forEach(x=>{if(x.tipo==="receita")a+=+x.valor;if(x.tipo==="despesa")b+=+x.valor;if(x.tipo==="investimento")c+=+x.valor});let label=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(month);$("monthLabel").textContent=label[0].toUpperCase()+label.slice(1);$("income").textContent=money(a);$("expense").textContent=money(b);$("invest").textContent=money(c);$("balance").textContent=money(a-b-c);$("dashList").innerHTML=rows.slice(0,6).map(txHtml).join("")||'<div class="empty">Nenhum lançamento neste mês.</div>';bindTx();let sums={};rows.filter(x=>x.tipo==="despesa").forEach(x=>{let n=x.categorias?.nome||"Sem categoria";sums[n]=(sums[n]||0)+Number(x.valor)});let vals=Object.entries(sums).sort((a,b)=>b[1]-a[1]),max=vals[0]?.[1]||1;$("categorySummary").innerHTML=vals.slice(0,7).map(([n,v])=>'<div class="barRow"><div class="barTop"><span>'+esc(n)+'</span><b>'+money(v)+'</b></div><div class="barTrack"><i style="width:'+Math.max(3,v/max*100)+'%"></i></div></div>').join("")||'<div class="empty">Sem despesas categorizadas.</div>';await loadReserve(true)}
async function loadFixed(){let r=await supabase.from("despesas_fixas").select("id,descricao,valor,vencimento,categoria_id,ativa,observacao,categorias(nome)").eq("user_id",user.id).order("vencimento");if(r.error){$("fixedList").innerHTML='<div class="empty">'+esc(r.error.message)+"</div>";return}let rows=r.data||[];$("fixedList").innerHTML=rows.length?rows.map(x=>'<div class="row"><div><strong>'+esc(x.descricao)+'</strong><small>Vence dia '+x.vencimento+" · "+esc(x.categorias?.nome||"Sem categoria")+" · "+(x.ativa?"Ativa":"Pausada")+'</small></div><div class="txRight"><b>'+money(x.valor)+'</b><div class="actions"><button data-fedit="'+x.id+'">Editar</button><button data-flaunch="'+x.id+'">Lançar mês</button><button data-fdel="'+x.id+'">Excluir</button></div></div></div>').join(""):'<div class="empty">Nenhuma despesa fixa cadastrada.</div>';document.querySelectorAll("[data-fedit]").forEach(b=>b.onclick=()=>openFixed(b.dataset.fedit));document.querySelectorAll("[data-fdel]").forEach(b=>b.onclick=()=>deleteFixed(b.dataset.fdel));document.querySelectorAll("[data-flaunch]").forEach(b=>b.onclick=()=>launchFixed(b.dataset.flaunch))}
function openFixed(id=null){editingFixed=id;$("fixedTitle").textContent=id?"Editar despesa fixa":"Nova despesa fixa";$("fixedForm").reset();$("fixedActive").checked=true;renderFixedCats();if(id)fillFixed(id);else openModal("fixedModal")}
async function fillFixed(id){let r=await supabase.from("despesas_fixas").select("*").eq("id",id).eq("user_id",user.id).single();if(r.error)return toast(r.error.message);let x=r.data;$("fixedDesc").value=x.descricao;$("fixedValue").value=x.valor;$("fixedDue").value=x.vencimento;$("fixedCat").value=x.categoria_id||"";$("fixedObs").value=x.observacao||"";$("fixedActive").checked=x.ativa;openModal("fixedModal")}
$("addFixed").onclick=()=>openFixed();$("fixedForm").onsubmit=async e=>{e.preventDefault();let d={descricao:$("fixedDesc").value.trim(),valor:Number($("fixedValue").value),vencimento:Number($("fixedDue").value),categoria_id:$("fixedCat").value||null,observacao:$("fixedObs").value.trim(),ativa:$("fixedActive").checked},r=editingFixed?await supabase.from("despesas_fixas").update(d).eq("id",editingFixed).eq("user_id",user.id):await supabase.from("despesas_fixas").insert({...d,user_id:user.id});if(r.error){$("fixedMsg").textContent=r.error.message;return}closeModal("fixedModal");toast("Despesa fixa salva");loadFixed()};
async function deleteFixed(id){if(!confirm("Excluir esta despesa fixa?"))return;let r=await supabase.from("despesas_fixas").delete().eq("id",id).eq("user_id",user.id);if(r.error)toast(r.error.message);else loadFixed()}
async function launchFixed(id){let r=await supabase.from("despesas_fixas").select("*").eq("id",id).eq("user_id",user.id).single();if(r.error)return toast(r.error.message);let x=r.data,d=new Date(month.getFullYear(),month.getMonth(),Math.min(x.vencimento,new Date(month.getFullYear(),month.getMonth()+1,0).getDate()));let data=iso(d),dup=await supabase.from("lancamentos").select("id").eq("user_id",user.id).eq("data",data).eq("descricao",x.descricao).limit(1);if(dup.data?.length)return toast("Essa conta já foi lançada neste mês");let ins=await supabase.from("lancamentos").insert({user_id:user.id,tipo:"despesa",data,valor:x.valor,descricao:x.descricao,categoria_id:x.categoria_id,status:"confirmado",recorrente:false});if(ins.error)toast(ins.error.message);else{toast("Despesa lançada no mês");loadFixed();loadDashboard()}}
async function loadCategories(){let r=await supabase.from("categorias").select("*").eq("user_id",user.id).order("tipo").order("nome");if(r.error)return;let rows=r.data||[];$("catList").innerHTML=rows.map(x=>'<div class="row"><div><strong>'+esc(x.nome)+'</strong><small>'+x.tipo+' · '+(x.ativa?"Ativa":"Inativa")+'</small></div><div class="actions"><button data-cedit="'+x.id+'">Editar</button><button data-ctoggle="'+x.id+'">'+(x.ativa?"Desativar":"Ativar")+'</button><button data-cdel="'+x.id+'">Excluir</button></div></div>').join("")||'<div class="empty">Nenhuma categoria.</div>';document.querySelectorAll("[data-cedit]").forEach(b=>b.onclick=()=>openCat(b.dataset.cedit));document.querySelectorAll("[data-ctoggle]").forEach(b=>b.onclick=()=>toggleCat(b.dataset.ctoggle));document.querySelectorAll("[data-cdel]").forEach(b=>b.onclick=()=>deleteCat(b.dataset.cdel))}
function openCat(id=null){editingCat=id;$("catTitle").textContent=id?"Editar categoria":"Nova categoria";$("catForm").reset();$("catActive").checked=true;if(id)fillCat(id);else openModal("catModal")}
async function fillCat(id){let r=await supabase.from("categorias").select("*").eq("id",id).eq("user_id",user.id).single();if(r.error)return;let x=r.data;$("catName").value=x.nome;$("catType").value=x.tipo;$("catActive").checked=x.ativa;openModal("catModal")}
$("addCat").onclick=()=>openCat();$("catForm").onsubmit=async e=>{e.preventDefault();let d={nome:$("catName").value.trim(),tipo:$("catType").value,ativa:$("catActive").checked},r=editingCat?await supabase.from("categorias").update(d).eq("id",editingCat).eq("user_id",user.id):await supabase.from("categorias").insert({...d,user_id:user.id});if(r.error){$("catMsg").textContent=r.error.message;return}closeModal("catModal");await loadCats();loadCategories();toast("Categoria salva")}
async function toggleCat(id){let x=cats.find(c=>c.id===id);if(!x)return;let r=await supabase.from("categorias").update({ativa:!x.ativa}).eq("id",id).eq("user_id",user.id);if(r.error)toast(r.error.message);else{await loadCats();loadCategories()}}
async function deleteCat(id){if(!confirm("Excluir categoria? Se estiver em uso, ela será mantida nos lançamentos."))return;let r=await supabase.from("categorias").delete().eq("id",id).eq("user_id",user.id);if(r.error)toast(r.error.message);else{await loadCats();loadCategories()}}
async function loadGoals(){let r=await supabase.from("metas").select("*").eq("user_id",user.id).order("created_at",{ascending:false});if(r.error)return;let rows=r.data||[];$("goalList").innerHTML=rows.map(x=>{let p=x.valor_meta?Math.min(100,Math.round(Number(x.valor_atual)/Number(x.valor_meta)*100)):0;return '<div class="row"><div style="flex:1"><strong>'+esc(x.nome)+'</strong><small>'+money(x.valor_atual)+" de "+money(x.valor_meta)+" · "+p+"%"+(x.data_fim?" · até "+new Date(x.data_fim+"T12:00:00").toLocaleDateString("pt-BR"):"")+'</small><div class="progress" style="margin:8px 0 0"><i style="width:'+p+'%"></i></div></div><div class="actions"><button data-gedit="'+x.id+'">Editar</button><button data-gdel="'+x.id+'">Excluir</button></div></div>'}).join("")||'<div class="empty">Nenhuma meta cadastrada.</div>';document.querySelectorAll("[data-gedit]").forEach(b=>b.onclick=()=>openGoal(b.dataset.gedit));document.querySelectorAll("[data-gdel]").forEach(b=>b.onclick=()=>deleteGoal(b.dataset.gdel))}
function openGoal(id=null){editingGoal=id;$("goalTitle").textContent=id?"Editar meta":"Nova meta";$("goalForm").reset();$("goalCurrent").value=0;if(id)fillGoal(id);else openModal("goalModal")}
async function fillGoal(id){let r=await supabase.from("metas").select("*").eq("id",id).eq("user_id",user.id).single();if(r.error)return;let x=r.data;$("goalName").value=x.nome;$("goalValue").value=x.valor_meta;$("goalCurrent").value=x.valor_atual;$("goalEnd").value=x.data_fim||"";openModal("goalModal")}
$("addGoal").onclick=()=>openGoal();$("goalForm").onsubmit=async e=>{e.preventDefault();let v=Number($("goalValue").value),cur=Number($("goalCurrent").value),d={nome:$("goalName").value.trim(),tipo:"financeira",valor_meta:v,valor_atual:cur,data_fim:$("goalEnd").value||null,status:cur>=v&&v>0?"concluida":"ativa"},r=editingGoal?await supabase.from("metas").update(d).eq("id",editingGoal).eq("user_id",user.id):await supabase.from("metas").insert({...d,user_id:user.id});if(r.error){$("goalMsg").textContent=r.error.message;return}closeModal("goalModal");loadGoals();toast("Meta salva")}
async function deleteGoal(id){if(!confirm("Excluir esta meta?"))return;let r=await supabase.from("metas").delete().eq("id",id).eq("user_id",user.id);if(r.error)toast(r.error.message);else loadGoals()}
async function loadReserve(silent=false){let r=await supabase.from("reservas").select("*").eq("user_id",user.id).single();if(r.error)return;let x=r.data,p=x.valor_meta?Math.min(100,Math.round(Number(x.valor_atual)/Number(x.valor_meta)*100)):0;["reservePct","reserveBigPct"].forEach(id=>$(id).textContent=p+"%");["reserveValue","reserveBigValue"].forEach(id=>$(id).textContent=money(x.valor_atual));["reserveGoal","reserveBigGoal"].forEach(id=>$(id).textContent="Meta: "+money(x.valor_meta));$("reserveBar").style.width=p+"%";$("reserveBigBar").style.width=p+"%";if(!silent){$("reserveTarget").value=x.valor_meta;$("reserveCurrent").value=x.valor_atual}}
$("editReserve").onclick=async()=>{await loadReserve(false);openModal("reserveModal")};$("reserveForm").onsubmit=async e=>{e.preventDefault();let r=await supabase.from("reservas").update({valor_meta:Number($("reserveTarget").value),valor_atual:Number($("reserveCurrent").value)}).eq("user_id",user.id);if(r.error){$("reserveMsg").textContent=r.error.message;return}closeModal("reserveModal");loadReserve();toast("Reserva atualizada")};
async function loadReports(){let endD=new Date(month.getFullYear(),month.getMonth()+1,0),from=new Date(endD);from.setMonth(from.getMonth()-5);let r=await supabase.from("lancamentos").select("data,tipo,valor").eq("user_id",user.id).gte("data",iso(new Date(from.getFullYear(),from.getMonth(),1))).lte("data",iso(endD)).neq("status","cancelado");if(r.error)return;let map={};for(let i=0;i<6;i++){let d=new Date(from.getFullYear(),from.getMonth()+i,1),k=d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0");map[k]={i,label:d.toLocaleDateString("pt-BR",{month:"short"}).replace(".",""),receita:0,despesa:0}};(r.data||[]).forEach(x=>{let k=x.data.slice(0,7);if(map[k])map[k][x.tipo]=(map[k][x.tipo]||0)+Number(x.valor)});let vals=Object.values(map),ti=vals.reduce((s,x)=>s+x.receita,0),te=vals.reduce((s,x)=>s+x.despesa,0);$("avgIncome").textContent=money(ti/6);$("avgExpense").textContent=money(te/6);$("saveRate").textContent=(ti?Math.round((ti-te)/ti*100):0)+"%";$("monthsAnalyzed").textContent=6;let max=Math.max(1,...vals.flatMap(x=>[x.receita,x.despesa]));$("reportBars").innerHTML=vals.map(x=>'<div class="reportRow"><b>'+esc(x.label)+'</b><div><div class="reportTrack"><i class="incomeBar" style="width:'+x.receita/max*100+'%"></i></div><small>Receitas '+money(x.receita)+' · Despesas '+money(x.despesa)+'</small></div></div>').join("")}
async function loadProfile(){let r=await supabase.from("perfis").select("*").eq("id",user.id).single();if(r.data){$("profileName").value=r.data.nome||"";$("profileEmail").value=user.email||""}}
$("profileForm").onsubmit=async e=>{e.preventDefault();let r=await supabase.from("perfis").upsert({id:user.id,nome:$("profileName").value.trim(),email:user.email},{onConflict:"id"});if(r.error){$("profileMsg").textContent=r.error.message;return}await supabase.auth.updateUser({data:{nome:$("profileName").value.trim()}});toast("Perfil salvo")};
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
$("importBtn").onclick=()=>$("fileInput").click();$("fileInput").onchange=async e=>{let f=e.target.files?.[0];if(!f)return;let text=await f.text(),lines=text.split(/\r?\n/).filter(Boolean),sep=text.includes(";")?";":",";let parsed=lines.map(line=>{let a=[],cur="",q=false;for(let ch of line){if(ch==='"')q=!q;else if(ch===sep&&!q){a.push(cur.trim().replace(/^"|"$/g,""));cur=""}else cur+=ch}a.push(cur.trim().replace(/^"|"$/g,""));return a});if(parsed.length<2){toast("CSV vazio");return}let h=parsed[0].map(x=>x.toLowerCase()),dateI=h.findIndex(x=>/data|date/.test(x)),descI=h.findIndex(x=>/descr|histor|memo/.test(x)),valI=h.findIndex(x=>/valor|value|amount/.test(x));if(dateI<0||descI<0||valI<0){toast("CSV precisa ter colunas de data, descrição e valor");return}let rows=[];for(let a of parsed.slice(1)){let d=a[dateI],desc=a[descI],v=a[valI];if(!d||!v)continue;let n=Number(String(v).replace(/\./g,"").replace(",",".").replace(/[^0-9.-]/g,""));if(!Number.isFinite(n))continue;let dt=d.includes("/")?d.split("/").reverse().join("-"):d.slice(0,10);rows.push({user_id:user.id,data:dt,tipo:n>=0?"receita":"despesa",valor:Math.abs(n),descricao:desc,status:"confirmado"})}if(!rows.length){toast("Nenhuma linha válida encontrada");return}let r=await supabase.from("lancamentos").insert(rows);if(r.error)toast(r.error.message);else{toast(rows.length+" lançamentos importados");loadDashboard();loadTransactions()}$("fileInput").value=""};
let onboardingUserChecked=null;
async function showOnboardingIfNeeded(){if(!user||onboardingUserChecked===user.id)return;onboardingUserChecked=user.id;let r=await supabase.from("configuracoes").select("id").eq("user_id",user.id).eq("chave","onboarding_visto").maybeSingle();if(r.error)return;if(r.data)return;openModal("onboardingModal")}
$("finishOnboarding").onclick=async()=>{if(!user)return;let r=await supabase.from("configuracoes").upsert({user_id:user.id,chave:"onboarding_visto",valor:"true"},{onConflict:"user_id,chave"});if(r.error){toast("Não foi possível salvar a confirmação.");return}closeModal("onboardingModal")};
async function enter(u){user=u;$("authView").classList.add("hide");$("app").classList.remove("hide");$("welcome").textContent="Olá, "+(u.user_metadata?.nome||u.email.split("@")[0]);await loadCats();await loadDashboard();await showOnboardingIfNeeded()}
const s=await supabase.auth.getSession();if(s.data.session)await enter(s.data.session.user);supabase.auth.onAuthStateChange((e,s)=>{if(s)enter(s.user);else{$("app").classList.add("hide");$("authView").classList.remove("hide")}});
