import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const supabase=createClient("https://jfomzksnsjytqhsuaqto.supabase.co","sb_publishable_zSAgcLcAEmNg655NHVt2YQ__nYB-qhg");
const $=x=>document.getElementById(x);let mode="login",user=null,month=new Date(new Date().getFullYear(),new Date().getMonth(),1),cats=[];
const money=v=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v)||0);
const start=()=>new Date(month.getFullYear(),month.getMonth(),1).toISOString().slice(0,10),end=()=>new Date(month.getFullYear(),month.getMonth()+1,0).toISOString().slice(0,10);
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));$("nameWrap").classList.toggle("hide",mode!=="signup");$("authBtn").textContent=mode==="login"?"Entrar":"Criar conta";$("authMsg").textContent=""});
$("authForm").onsubmit=async e=>{e.preventDefault();$("authMsg").textContent="Processando...";let email=$("email").value.trim(),password=$("password").value,name=$("name").value.trim();let r=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{nome:name}}});if(r.error){$("authMsg").textContent=r.error.message;return}if(mode==="signup"&&!r.data.session){$("authMsg").style.color="#8fe7b3";$("authMsg").textContent="Conta criada. Verifique seu e-mail para confirmar."}};
$("logout").onclick=()=>supabase.auth.signOut();$("prev").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()-1,1);load()};$("next").onclick=()=>{month=new Date(month.getFullYear(),month.getMonth()+1,1);load()};
$("add").onclick=()=>{$("modal").classList.remove("hide");$("date").value=new Date().toISOString().slice(0,10);$("txMsg").textContent=""};$("close").onclick=()=>$("modal").classList.add("hide");$("modal").onclick=e=>{if(e.target===$("modal"))$("modal").classList.add("hide")};$("type").onchange=renderCats;
async function loadCats(){let r=await supabase.from("categorias").select("id,nome,tipo").eq("user_id",user.id).eq("ativa",true).order("nome");cats=r.data||[];renderCats()}
function renderCats(){let t=$("type").value;$("cat").innerHTML=cats.filter(c=>c.tipo===t).map(c=>'<option value="'+c.id+'">'+c.nome+"</option>").join("")}
$("txForm").onsubmit=async e=>{e.preventDefault();$("txMsg").textContent="Salvando...";let r=await supabase.from("lancamentos").insert({user_id:user.id,tipo:$("type").value,data:$("date").value,valor:Number($("value").value),descricao:$("desc").value.trim(),categoria_id:$("cat").value||null,recorrente:$("rec").checked,recorrencia:$("rec").checked?"mensal":null,status:"confirmado"});if(r.error){$("txMsg").textContent=r.error.message;return}$("txForm").reset();$("modal").classList.add("hide");load()};
async function load(){let label=new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(month);$("monthLabel").textContent=label.charAt(0).toUpperCase()+label.slice(1);let r=await supabase.from("lancamentos").select("id,data,tipo,descricao,valor,status,categorias(nome)").eq("user_id",user.id).gte("data",start()).lte("data",end()).neq("status","cancelado").order("data",{ascending:false});let rows=r.data||[],a=0,b=0,c=0;rows.forEach(x=>{if(x.tipo==="receita")a+=+x.valor;if(x.tipo==="despesa")b+=+x.valor;if(x.tipo==="investimento")c+=+x.valor});$("income").textContent=money(a);$("expense").textContent=money(b);$("invest").textContent=money(c);$("balance").textContent=money(a-b-c);$("count").textContent=rows.length+" lançamento"+(rows.length===1?"":"s");$("list").innerHTML=rows.length?rows.map(x=>'<div class="tx"><div><strong>'+esc(x.descricao)+'</strong><small>'+new Date(x.data+"T12:00:00").toLocaleDateString("pt-BR")+" · "+esc(x.categorias?.nome||"Sem categoria")+'</small></div><div class="amount '+x.tipo+'">'+(x.tipo==="receita"?"+":"-")+money(x.valor)+"</div></div>").join(""):'<div class="empty">Nenhum lançamento neste mês.</div>'}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
async function enter(u){user=u;$("authView").classList.add("hide");$("app").classList.remove("hide");$("welcome").textContent="Olá, "+(u.user_metadata?.nome||u.email.split("@")[0]);await loadCats();await load()}
const s=await supabase.auth.getSession();if(s.data.session)enter(s.data.session.user);supabase.auth.onAuthStateChange((e,s)=>{if(s)enter(s.user);else{$("app").classList.add("hide");$("authView").classList.remove("hide")}});